[package]
name = "ide-diagnostics"
version = "0.0.0"
edition = "2024"

[dependencies]
hir.workspace = true
hir-ty.workspace = true
ide-db.workspace = true
rowan.workspace = true
rustc-hash.workspace = true
salsa.workspace = true
syntax.workspace = true
tracing.workspace = true
triomphe.workspace = true
vfs.workspace = true
