[package]
name = "ide-db"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
base-db.workspace = true
hir.workspace = true
hir-def.workspace = true
hir-expand.workspace = true
hir-ty.workspace = true
line-index.workspace = true
rowan.workspace = true
salsa.workspace = true
triomphe.workspace = true
vfs.workspace = true

[dev-dependencies]
camino.workspace = true
tempfile = "3"
zip.workspace = true
