[package]
name = "hir-ty"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
base-db.workspace = true
hir.workspace = true
hir-def.workspace = true
hir-expand.workspace = true
rowan.workspace = true
rust-asm.workspace = true
rustc-hash.workspace = true
salsa.workspace = true
stacksafe.workspace = true
syntax.workspace = true
triomphe.workspace = true
vfs.workspace = true

[dev-dependencies]
base-db.workspace = true
camino.workspace = true
hir-def.workspace = true
ide-diagnostics.workspace = true
insta.workspace = true
line-index.workspace = true
rowan.workspace = true
rustc-hash.workspace = true
tempfile = "3"
triomphe.workspace = true
vfs.workspace = true
zip.workspace = true

