[package]
name = "ide"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
dashmap.workspace = true
hir.workspace = true
hir-expand.workspace = true
hir-ty.workspace = true
ide-db.workspace = true
ide-diagnostics.workspace = true
parking_lot.workspace = true
project-model.workspace = true
rayon.workspace = true
rowan.workspace = true
rustc-hash.workspace = true
syntax.workspace = true
triomphe.workspace = true
vfs.workspace = true

[dev-dependencies]
insta.workspace = true
